<?php

/**
 * PHP version 5.6
 *
 * @package   Manifest
 * @author    Config Generator <jenkins@svn.logics.net.au>
 * @copyright 2016 Andrey Mashukov
 * @license   http://www.gefest.com.au/license Gefest proprietary license
 * @version   SVN: $Date: 2016-09-30 23:05:14 +0930 (Fri, 30 Sep 2016) $ $Revision: 14 $
 * @link      $HeadURL: https://svn.logics.net.au/solitaire/shorty/trunk/manifest/exceptions.php $
 */

/**
 * Automatically generated file, do not modify
 *
 * @donottranslate
 */

(defined("EXCEPTION_CANNOT_RUN_TESSERACT") === true) ? : define("EXCEPTION_CANNOT_RUN_TESSERACT", 1);
(defined("EXCEPTION_ERROR_READING_TEXT_FILE") === true) ? : define("EXCEPTION_ERROR_READING_TEXT_FILE", 2);
(defined("EXCEPTION_INVALID_RECORD_TYPE") === true) ? : define("EXCEPTION_INVALID_RECORD_TYPE", 3);
(defined("EXCEPTION_NO_RECORDS_SELECTED") === true) ? : define("EXCEPTION_NO_RECORDS_SELECTED", 4);
(defined("EXCEPTION_USELESS_OPERATION") === true) ? : define("EXCEPTION_USELESS_OPERATION", 5);
(defined("EXCEPTION_MISSING_DAO_DESCRIPTION") === true) ? : define("EXCEPTION_MISSING_DAO_DESCRIPTION", 6);
(defined("EXCEPTION_AMBIGUOUS_SLOT") === true) ? : define("EXCEPTION_AMBIGUOUS_SLOT", 7);
(defined("EXCEPTION_NONEXISTENT_SLOT") === true) ? : define("EXCEPTION_NONEXISTENT_SLOT", 8);
(defined("EXCEPTION_USE_METHOD_GET") === true) ? : define("EXCEPTION_USE_METHOD_GET", 9);
(defined("EXCEPTION_NO_IMPLEMENTATION_OF_INTERFACE_EXISTS") === true) ? : define("EXCEPTION_NO_IMPLEMENTATION_OF_INTERFACE_EXISTS", 10);
(defined("EXCEPTION_ATTEMPTED_SLOT_REDEFINITION") === true) ? : define("EXCEPTION_ATTEMPTED_SLOT_REDEFINITION", 11);
(defined("EXCEPTION_WRONG_DAO_FORMAT") === true) ? : define("EXCEPTION_WRONG_DAO_FORMAT", 12);
(defined("EXCEPTION_PARAMETER_MISMATCH") === true) ? : define("EXCEPTION_PARAMETER_MISMATCH", 13);
(defined("EXCEPTION_PARAMETERS_MISMATCH") === true) ? : define("EXCEPTION_PARAMETERS_MISMATCH", 14);
(defined("EXCEPTION_CONSTANT_UNDEFINED") === true) ? : define("EXCEPTION_CONSTANT_UNDEFINED", 15);
(defined("EXCEPTION_RPM_EXECUTION_FAILED") === true) ? : define("EXCEPTION_RPM_EXECUTION_FAILED", 16);
(defined("EXCEPTION_CANNOT_INSTALL_PACKAGE") === true) ? : define("EXCEPTION_CANNOT_INSTALL_PACKAGE", 17);
(defined("EXCEPTION_CANNOT_ENABLE_PACKAGE") === true) ? : define("EXCEPTION_CANNOT_ENABLE_PACKAGE", 18);
(defined("EXCEPTION_RESTART_REQUIRED") === true) ? : define("EXCEPTION_RESTART_REQUIRED", 19);
(defined("EXCEPTION_EXIT") === true) ? : define("EXCEPTION_EXIT", 20);
(defined("EXCEPTION_CANNOT_SET_CONNECTION_SETTINGS") === true) ? : define("EXCEPTION_CANNOT_SET_CONNECTION_SETTINGS", 21);
(defined("EXCEPTION_UNKNOWN_SQL_DRIVER") === true) ? : define("EXCEPTION_UNKNOWN_SQL_DRIVER", 22);
(defined("EXCEPTION_NO_MYSQL_CONNECTION_DETAILS") === true) ? : define("EXCEPTION_NO_MYSQL_CONNECTION_DETAILS", 23);
(defined("EXCEPTION_NO_POSTGRESQL_CONNECTION_DETAILS") === true) ? : define("EXCEPTION_NO_POSTGRESQL_CONNECTION_DETAILS", 24);
(defined("EXCEPTION_STATE_MACHINE_INCOMPLETE") === true) ? : define("EXCEPTION_STATE_MACHINE_INCOMPLETE", 25);
(defined("EXCEPTION_AMBIGUOUS_TRANSITION") === true) ? : define("EXCEPTION_AMBIGUOUS_TRANSITION", 26);
(defined("EXCEPTION_TRANSITION_FOR_UNKNOWN_STATE") === true) ? : define("EXCEPTION_TRANSITION_FOR_UNKNOWN_STATE", 27);
(defined("EXCEPTION_INVALID_NAMETRACE") === true) ? : define("EXCEPTION_INVALID_NAMETRACE", 28);
(defined("EXCEPTION_VALUES_AND_ATTRIBUTE_VALUES_MISMATCH") === true) ? : define("EXCEPTION_VALUES_AND_ATTRIBUTE_VALUES_MISMATCH", 29);
(defined("EXCEPTION_RETURN_TYPE_VALUE_IS_WRONG") === true) ? : define("EXCEPTION_RETURN_TYPE_VALUE_IS_WRONG", 30);
(defined("EXCEPTION_VALID_NODE_TYPE_NOT_SPECIFIED") === true) ? : define("EXCEPTION_VALID_NODE_TYPE_NOT_SPECIFIED", 31);
(defined("EXCEPTION_UNABLE_TO_OPEN_SCHEMA") === true) ? : define("EXCEPTION_UNABLE_TO_OPEN_SCHEMA", 32);
(defined("EXCEPTION_VALID_NAMETRACE_DESCRIPTOR_REQUIRED") === true) ? : define("EXCEPTION_VALID_NAMETRACE_DESCRIPTOR_REQUIRED", 33);
(defined("EXCEPTION_UNABLE_TO_LOCATE_ROOT_ELEMENT") === true) ? : define("EXCEPTION_UNABLE_TO_LOCATE_ROOT_ELEMENT", 34);
(defined("EXCEPTION_UNABLE_TO_TRANSLATE") === true) ? : define("EXCEPTION_UNABLE_TO_TRANSLATE", 35);
(defined("EXCEPTION_DISABLED_CACHE_NAMETRACES_SHOULD_BE_SET") === true) ? : define("EXCEPTION_DISABLED_CACHE_NAMETRACES_SHOULD_BE_SET", 36);
(defined("EXCEPTION_UNABLE_TO_RETRIEVE") === true) ? : define("EXCEPTION_UNABLE_TO_RETRIEVE", 37);
(defined("EXCEPTION_DESCRIPTION_SHOULD_BE_OVERLOADED") === true) ? : define("EXCEPTION_DESCRIPTION_SHOULD_BE_OVERLOADED", 38);
(defined("EXCEPTION_DIFFERENT_WIDGET_DESCRIPTION") === true) ? : define("EXCEPTION_DIFFERENT_WIDGET_DESCRIPTION", 39);
(defined("EXCEPTION_NO_SUCH_TARGET") === true) ? : define("EXCEPTION_NO_SUCH_TARGET", 40);
(defined("EXCEPTION_NO_SUCH_SOURCE") === true) ? : define("EXCEPTION_NO_SUCH_SOURCE", 41);
(defined("EXCEPTION_NO_SUCH_SCHEMA") === true) ? : define("EXCEPTION_NO_SUCH_SCHEMA", 42);
(defined("EXCEPTION_INVALID_REQUEST") === true) ? : define("EXCEPTION_INVALID_REQUEST", 43);
(defined("EXCEPTION_INVALID_UPLOAD") === true) ? : define("EXCEPTION_INVALID_UPLOAD", 44);
(defined("EXCEPTION_WEBSITE_MAP_NOT_EXISTS") === true) ? : define("EXCEPTION_WEBSITE_MAP_NOT_EXISTS", 45);
(defined("EXCEPTION_PAGE_IS_NOT_A_SCENARIOPAGE") === true) ? : define("EXCEPTION_PAGE_IS_NOT_A_SCENARIOPAGE", 46);
(defined("EXCEPTION_TEMPLATE_IS_REQUIRED") === true) ? : define("EXCEPTION_TEMPLATE_IS_REQUIRED", 47);
(defined("EXCEPTION_NO_WAY_OUT_OF_ACTION_STATE") === true) ? : define("EXCEPTION_NO_WAY_OUT_OF_ACTION_STATE", 48);
(defined("EXCEPTION_BAD_REQUEST") === true) ? : define("EXCEPTION_BAD_REQUEST", 49);
(defined("EXCEPTION_INVALID_SCHEMA") === true) ? : define("EXCEPTION_INVALID_SCHEMA", 50);
(defined("EXCEPTION_XML_PARSING_ERROR") === true) ? : define("EXCEPTION_XML_PARSING_ERROR", 51);
(defined("EXCEPTION_UNABLE_TO_EXPAND") === true) ? : define("EXCEPTION_UNABLE_TO_EXPAND", 52);
(defined("EXCEPTION_ROOT_INDEX_NOT_VALID") === true) ? : define("EXCEPTION_ROOT_INDEX_NOT_VALID", 53);
(defined("EXCEPTION_UNUSED_ITEMS") === true) ? : define("EXCEPTION_UNUSED_ITEMS", 54);
(defined("EXCEPTION_INVALID_DOCUMENT") === true) ? : define("EXCEPTION_INVALID_DOCUMENT", 55);
(defined("EXCEPTION_UNABLE_TO_LOAD_SCHEMA") === true) ? : define("EXCEPTION_UNABLE_TO_LOAD_SCHEMA", 56);
(defined("EXCEPTION_UNABLE_TO_GET_EXTERNAL") === true) ? : define("EXCEPTION_UNABLE_TO_GET_EXTERNAL", 57);
(defined("EXCEPTION_NAME_SHOULD_BE_SPECIFIED") === true) ? : define("EXCEPTION_NAME_SHOULD_BE_SPECIFIED", 58);
(defined("EXCEPTION_TYPE_SHOULD_BE_SPECIFIED") === true) ? : define("EXCEPTION_TYPE_SHOULD_BE_SPECIFIED", 59);
(defined("EXCEPTION_UNABLE_TO_RETURN") === true) ? : define("EXCEPTION_UNABLE_TO_RETURN", 60);
(defined("EXCEPTION_NO_ELEMENT_OF_TYPE") === true) ? : define("EXCEPTION_NO_ELEMENT_OF_TYPE", 61);
(defined("EXCEPTION_LOAD_XML_FAILED") === true) ? : define("EXCEPTION_LOAD_XML_FAILED", 62);
(defined("EXCEPTION_UNKNOWN_DOCUMENT_TYPE") === true) ? : define("EXCEPTION_UNKNOWN_DOCUMENT_TYPE", 63);
(defined("EXCEPTION_UNKNOWN_PATH") === true) ? : define("EXCEPTION_UNKNOWN_PATH", 64);
(defined("EXCEPTION_NO_TRANSLATION_FOR_DOCUMENT_TYPE") === true) ? : define("EXCEPTION_NO_TRANSLATION_FOR_DOCUMENT_TYPE", 65);
(defined("EXCEPTION_NO_TRANSLATION_METHOD") === true) ? : define("EXCEPTION_NO_TRANSLATION_METHOD", 66);
(defined("EXCEPTION_TRANSLATION_FAULT") === true) ? : define("EXCEPTION_TRANSLATION_FAULT", 67);
(defined("EXCEPTION_WRONG_DISCOVERY_MODE") === true) ? : define("EXCEPTION_WRONG_DISCOVERY_MODE", 68);
(defined("EXCEPTION_NO_FLATTENED_ARRAY") === true) ? : define("EXCEPTION_NO_FLATTENED_ARRAY", 69);

?>
